### ISSUE TITLE
Gauge graph, partial pie and partial donut graphs

### ISSUE THREAD

**Issue by JamesMcIntosh** [google/charts#121]
By adding a parameter for arc length to the arc renderer. Using the existing configuration at least three additional graph can be accomplished, see images:

Gauge graph
![arc-graph-gauge](https://user-images.githubusercontent.com/455724/45190942-8f119c00-b294-11e8-947b-e2010a212a3a.png)
Partial pie
![arc-graph-partial-pie](https://user-images.githubusercontent.com/455724/45190944-8f119c00-b294-11e8-9fc5-bb0e4a5dba2f.png)
Partial donut
![arc-graph-partial-donut](https://user-images.githubusercontent.com/455724/45190943-8f119c00-b294-11e8-874a-a7e572bda4aa.png)

**Comment by VyMajoris** [comment]
I take that this has not been released yet? 

 [This page](https://google.github.io/charts/flutter/example/pie_charts/gauge) details how to create a gauge graph, but the arcLength is not present on current version, 0.4.0

**Comment by JamesMcIntosh** [comment]
@VyMajoris You can use git repos as a dependency and specify "dependency_overrides" element in your pubspec to get early access to it.

https://www.dartlang.org/tools/pub/dependencies#git-packages
https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

Add something like this to your pubspec.yaml (untested).
```
dev_dependencies:
  charts_flutter: 0.4.0

dependency_overrides:
  charts_common:
    git:
      url: git@github.com:google/charts.git
      path: charts_common
  charts_flutter:
    git:
      url: git@github.com:google/charts.git
      path: charts_flutter
```
