### ISSUE TITLE
0.4.0 mismatched

### ISSUE THREAD

**Issue by bagintz** [google/charts#156]
The published version pulled through pubspec.yaml does not contain the same code as in master?  Is there something I need to do on my end, or is it just waiting for a version bump.  Specifically I was trying to get the "Gauge" chart.

Thanks

**Comment by CarsonHolzheimer** [comment]
For the latest commit:
```
charts_flutter:
      git:
        url: http://github.com/google/charts.git
        path: charts_flutter
        ref: 2b0f52a
```

**Comment by bagintz** [comment]
@CarsonHolzheimer 

```
Error on line 18, column 11: Invalid description: "../charts_common/" is a relative path, but this isn't a local pubspec.
    path: ../charts_common/
          ^^^^^^^^^^^^^^^^^

pub get failed (65)

```

**Comment by VyMajoris** [comment]
@CarsonHolzheimer
 This is how you want to set up your pubspec:

```
dependencies:
  charts_flutter: 0.4.0

dependency_overrides:
  charts_common:
    git:
      url: git://github.com/google/charts.git
      path: charts_common
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
```
