### ISSUE TITLE
Error: The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297

### ISSUE THREAD

**Issue by firedevelop** [google/charts#212]
Hello!
I want to use this nice charts, but I have some issues. Please can you help me?

I did **flutter upgrade**
```
DHJW-iMac-2011:charts admin$ flutter upgrade
Upgrading Flutter from /Applications/flutter...
Already up to date.
DHJW-iMac-2011:charts admin$ flutter upgrade
Upgrading Flutter from /Applications/flutter...
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G5019, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
[✓] Connected device (1 available)

• No issues found!
DHJW-iMac-2011:charts admin$ 
```

I paste the line **charts_flutter: ^0.6.0:** in my **pubspec.yaml**:
```
name: charts_flutter
version: 0.6.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  # charts_common: 0.6.0
  charts_common:
    path: ../charts_common/
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.15.2
  logging: any
  meta: ^1.1.1


dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
```

I proyect are in the path:
```
DHJW-iMac-2011:charts admin$ pwd
/Volumes/6TB/production-VARIOS/Github/id0000150_flutter_dart_example/id0000150_9/charts
```

Also I did **flutter packages get**
```
DHJW-iMac-2011:charts_flutter admin$ pwd
/Volumes/6TB/production-VARIOS/Github/id0000150_flutter_dart_example/id0000150_9/charts/charts_flutter
DHJW-iMac-2011:charts_flutter admin$ flutter packages get
Running "flutter packages get" in charts_flutter...              
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because charts_flutter depends on charts_common from path which requires SDK version >=2.1.0 <3.0.0, version solving failed.
 
pub get failed (1)
DHJW-iMac-2011:charts_flutter admin$ 
```

Please any help, will be appreiate.
Thanks so much!
