### ISSUE TITLE
some of the labels did not show in piechart

### ISSUE THREAD

**Issue by pickupsb** [google/charts#349]
i set four labels,but only show two,how to fix this?
![image](https://user-images.githubusercontent.com/8519103/67665861-8357cc00-f9a5-11e9-914c-47ec8e7d9eda.png)

**Comment by didyqian** [comment]
I also encountered the same problem. Is there a solution?

**Comment by me-singh** [comment]
I also have the same problem. Does anyone have any alternate solution to show these labels.

**Comment by rubik-d** [comment]
Same issue. It seems that lables got clipped or hidden impacted by its diameter and another label in proximity. Basically renders the piechart unusable.

**Comment by darkstarx** [comment]
Hello! Is here any maintainer?

**Comment by darkstarx** [comment]
```
  charts_flutter:
    git:
      url: git@github.com:darkstarx/charts.git
      path: charts_flutter
      ref: master
```

```
    return charts.PieChart(
      [
        charts.Series<List, String>(
          id: id,
          data: data,
          domainFn: (e, i) => e[0],
          measureFn: (e, i) => e[1],
          colorFn: (e, i) => e[2],
          labelAccessorFn: (e, i) => '${e[1]}%',
        ),
      ],
      behaviors: [
        charts.DatumLegend(
          position: charts.BehaviorPosition.bottom,
          entryTextStyle: charts.TextStyleSpec(fontSize: 13),
          cellPadding: const EdgeInsets.symmetric(vertical: 2.0),
          horizontalFirst: false,
        ),
      ],
      defaultRenderer: charts.ArcRendererConfig(
        arcRendererDecorators: [
          charts.ArcLabelDecorator(
            labelPosition: charts.ArcLabelPosition.outside,
            labelPadding: 0,
            leaderLineStyleSpec: charts.ArcLabelLeaderLineStyleSpec(
              length: 4.0,
            ),
            insideLabelStyleSpec: charts.TextStyleSpec(
              fontSize: 11,
            ),
            outsideLabelStyleSpec: charts.TextStyleSpec(
              fontSize: 11,
            ),
            showLeaderLines: false,
            constraintLabels: false,    // << HERE YOU ARE
          )
        ],
      ),
      animate: true,
    );
```

**Comment by bahung1221** [comment]
Same problem here, I confirmed that the fork of @darkstarx worked 🎉

**Comment by darkstarx** [comment]
Hi guys! I've updated my fork of this repo up to the google's master with support of null-safety. It includes fix of this issue and some other useful things and it works fine with stable branch of flutter.
You can use it like this:
```
  charts_flutter:
    git:
      url: git@github.com:darkstarx/charts.git
      path: charts_flutter
      ref: master
```

The old version (for flutter v1) now is `for_flutter1`, you can use it like this:
```
  charts_flutter:
    git:
      url: git@github.com:darkstarx/charts.git
      path: charts_flutter
      ref: for_flutter1
```
