### ISSUE TITLE
The getter 'body1' isn't defined...

### ISSUE THREAD

**Issue by Wissperwind** [google/charts#669]
Hi,

Could you please release a new version of flutter charts?
I already opend an issue about this problem, and you fixed the one place in your code, where this was used.
But that doesn't help us running this library if you don't release a new version.
Please do so, so that we can use the latest master branch version of flutter again!

**Comment by deepak786** [comment]
@Wissperwind until the new version is not released with the fix, you can override the charts_flutter from master because the issue is already solved in the branch.
```
dependency_overrides:
 charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
```
