### ISSUE TITLE
Fix: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null

### ISSUE THREAD

**Issue by akshaynjarangal** [google/charts#771]
if anyone facing the warning with charts_flutter package after the `flutter 3.0` update , you can simply remove null check `'!'` on respective code lines, and rebuild the app. @google-admin please fix the issue on your side.

<img width="1147" alt="Screenshot 2022-05-23 at 1 12 39 PM" src="https://user-images.githubusercontent.com/63861163/169769312-8270d121-2a5f-41a6-8bc0-7cc0f1d74faa.png">

**Comment by Wissperwind** [comment]
Same problem here. Please release soon.

**Comment by kennenfromchina** [comment]
Temporary fix
change your pubspec.yaml to this
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  charts_flutter: ^0.12.0
dependency_overrides:
  # add override of charts_flutter
  charts_flutter:
    git:
      url: https://github.com/kennenfromchina/charts.git
      path: charts_flutter
      ref: fix_flutter3.0
```
